// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvuIr0-2zCn_QvUCnOStzlpm6rq49UT14',
    appId: '1:1397283656:web:8a2f9a89a448caa83e717d',
    messagingSenderId: '1397283656',
    projectId: 'travel-companion-a27a6',
    authDomain: 'travel-companion-a27a6.firebaseapp.com',
    databaseURL: 'https://travel-companion-a27a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-companion-a27a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wAoFYTdJ-5yV9y8aIzt_X_MgY3obKAY',
    appId: '1:1397283656:android:180dcc061fcc282e3e717d',
    messagingSenderId: '1397283656',
    projectId: 'travel-companion-a27a6',
    databaseURL: 'https://travel-companion-a27a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-companion-a27a6.appspot.com',
  );
}
